language: objective-c
osx_image: xcode8.2
xcode_project: Smart4SURE.xcodeproj
xcode_scheme: Smart4SURE
cache:
- bundler
before_install:
- bundle update
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
script:
- "travis_wait 30 ./travis/build.sh"
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAICA2M6XGX62Q4NTQ
  secret_access_key:
    secure: cl6zB7V5ua5tkGJh9dH67h7WRwPlGDy778RLciVJMRsUtPBnIAL/yVpmM86MtYzO/ND5z3r86CeGQ3JP1pVzlUCnEoY2MsGFSNLp2Dszu24nL8V/JKeHa7eXkJCVxgEwGkKEDxhqOAYrFqnB7WboFCYK3mduET9UQQ1nSRUA1fzjcsueKgr0/6HleKujH9mu+SYlaHWGsNYt2LR7cna68VhhhNEnKi3QvEbTF8NYV1yrUKFHbOSHPfKtRyhv8ojLw84sD5c3NZVZ6FnFForIxa1C2h1vc7zQZ9lNXak3/NXbYEopUDiznfakt4ru62sf9TdhCLA7dvWhxPPK1ycqBXes0btdsVtNY+yyjW+2NFweL04UTS5tSIQ2iIbUbZK2K/NXCa5mTEdXlpvceMUV4uK+VW76CyJqWBK5P1vCQdpzXYqeNr3RIpy/BaMS7kcg1FRIVmeGpDEmBsybQk3EFDmqznj9nFclmIBuxihMZvXPRu24hYcuP7lvkWip5WlhW3TMKn/wZuJ3JrylmWgRtVwVDVpgQn1hKcni6BvfittApy05wdnzKYTxRIZVascPWGSWQsoMgXv82Lnr+yJ24tOQqVRYYKZ2vr9IlhLaQKDNTG775bgVGVwORlluf8fxHIIZcSv5Ay2X0Y3cMJBqYxkoV5C5XPyfMXHz0t5uPxM=
  bucket: ios-apps.sagebridge.org
  local-dir: build
  upload-dir: ci/$TRAVIS_XCODE_SCHEME/$TRAVIS_BRANCH
  on:
    branch: master
